// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: firm.proto

package firm_service

import (
	user_service "/user_service"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Firm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner   *user_service.User `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Enabled bool               `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *Firm) Reset() {
	*x = Firm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_firm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Firm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Firm) ProtoMessage() {}

func (x *Firm) ProtoReflect() protoreflect.Message {
	mi := &file_firm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Firm.ProtoReflect.Descriptor instead.
func (*Firm) Descriptor() ([]byte, []int) {
	return file_firm_proto_rawDescGZIP(), []int{0}
}

func (x *Firm) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Firm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Firm) GetOwner() *user_service.User {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Firm) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetFirmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirmId int32 `protobuf:"varint,1,opt,name=firmId,proto3" json:"firmId,omitempty"`
}

func (x *GetFirmRequest) Reset() {
	*x = GetFirmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_firm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFirmRequest) ProtoMessage() {}

func (x *GetFirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFirmRequest.ProtoReflect.Descriptor instead.
func (*GetFirmRequest) Descriptor() ([]byte, []int) {
	return file_firm_proto_rawDescGZIP(), []int{1}
}

func (x *GetFirmRequest) GetFirmId() int32 {
	if x != nil {
		return x.FirmId
	}
	return 0
}

type CreateFirmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner   *user_service.User `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Enabled bool               `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *CreateFirmRequest) Reset() {
	*x = CreateFirmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_firm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFirmRequest) ProtoMessage() {}

func (x *CreateFirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFirmRequest.ProtoReflect.Descriptor instead.
func (*CreateFirmRequest) Descriptor() ([]byte, []int) {
	return file_firm_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFirmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFirmRequest) GetOwner() *user_service.User {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *CreateFirmRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_firm_proto protoreflect.FileDescriptor

var file_firm_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x69, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x69,
	0x72, 0x6d, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66,
	0x0a, 0x04, 0x46, 0x69, 0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x72,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x72, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x72, 0x6d, 0x49, 0x64,
	0x22, 0x63, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x72, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x32, 0x71, 0x0a, 0x0b, 0x46, 0x69, 0x72, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x69, 0x72, 0x6d, 0x12,
	0x14, 0x2e, 0x66, 0x69, 0x72, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x72, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x66, 0x69, 0x72, 0x6d, 0x2e, 0x46, 0x69, 0x72,
	0x6d, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x72,
	0x6d, 0x12, 0x17, 0x2e, 0x66, 0x69, 0x72, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x66, 0x69, 0x72,
	0x6d, 0x2e, 0x46, 0x69, 0x72, 0x6d, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x2f, 0x66, 0x69, 0x72,
	0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_firm_proto_rawDescOnce sync.Once
	file_firm_proto_rawDescData = file_firm_proto_rawDesc
)

func file_firm_proto_rawDescGZIP() []byte {
	file_firm_proto_rawDescOnce.Do(func() {
		file_firm_proto_rawDescData = protoimpl.X.CompressGZIP(file_firm_proto_rawDescData)
	})
	return file_firm_proto_rawDescData
}

var file_firm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_firm_proto_goTypes = []interface{}{
	(*Firm)(nil),              // 0: firm.Firm
	(*GetFirmRequest)(nil),    // 1: firm.GetFirmRequest
	(*CreateFirmRequest)(nil), // 2: firm.CreateFirmRequest
	(*user_service.User)(nil), // 3: user.User
}
var file_firm_proto_depIdxs = []int32{
	3, // 0: firm.Firm.owner:type_name -> user.User
	3, // 1: firm.CreateFirmRequest.owner:type_name -> user.User
	1, // 2: firm.FirmService.GetFirm:input_type -> firm.GetFirmRequest
	2, // 3: firm.FirmService.CreateFirm:input_type -> firm.CreateFirmRequest
	0, // 4: firm.FirmService.GetFirm:output_type -> firm.Firm
	0, // 5: firm.FirmService.CreateFirm:output_type -> firm.Firm
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_firm_proto_init() }
func file_firm_proto_init() {
	if File_firm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_firm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Firm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_firm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFirmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_firm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFirmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_firm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_firm_proto_goTypes,
		DependencyIndexes: file_firm_proto_depIdxs,
		MessageInfos:      file_firm_proto_msgTypes,
	}.Build()
	File_firm_proto = out.File
	file_firm_proto_rawDesc = nil
	file_firm_proto_goTypes = nil
	file_firm_proto_depIdxs = nil
}
