// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: upvote.proto

package upvote_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VotePayload_ResourceType int32

const (
	VotePayload_FIRM   VotePayload_ResourceType = 0
	VotePayload_ANSWER VotePayload_ResourceType = 1
)

// Enum value maps for VotePayload_ResourceType.
var (
	VotePayload_ResourceType_name = map[int32]string{
		0: "FIRM",
		1: "ANSWER",
	}
	VotePayload_ResourceType_value = map[string]int32{
		"FIRM":   0,
		"ANSWER": 1,
	}
)

func (x VotePayload_ResourceType) Enum() *VotePayload_ResourceType {
	p := new(VotePayload_ResourceType)
	*p = x
	return p
}

func (x VotePayload_ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VotePayload_ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_upvote_proto_enumTypes[0].Descriptor()
}

func (VotePayload_ResourceType) Type() protoreflect.EnumType {
	return &file_upvote_proto_enumTypes[0]
}

func (x VotePayload_ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VotePayload_ResourceType.Descriptor instead.
func (VotePayload_ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_upvote_proto_rawDescGZIP(), []int{0, 0}
}

type VotePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId   int32                    `protobuf:"varint,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	UserId       int32                    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	VoteDir      int32                    `protobuf:"varint,3,opt,name=voteDir,proto3" json:"voteDir,omitempty"`
	ResourceType VotePayload_ResourceType `protobuf:"varint,4,opt,name=resourceType,proto3,enum=upvote.VotePayload_ResourceType" json:"resourceType,omitempty"`
}

func (x *VotePayload) Reset() {
	*x = VotePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upvote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VotePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotePayload) ProtoMessage() {}

func (x *VotePayload) ProtoReflect() protoreflect.Message {
	mi := &file_upvote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotePayload.ProtoReflect.Descriptor instead.
func (*VotePayload) Descriptor() ([]byte, []int) {
	return file_upvote_proto_rawDescGZIP(), []int{0}
}

func (x *VotePayload) GetResourceId() int32 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *VotePayload) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VotePayload) GetVoteDir() int32 {
	if x != nil {
		return x.VoteDir
	}
	return 0
}

func (x *VotePayload) GetResourceType() VotePayload_ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return VotePayload_FIRM
}

type VoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upvote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upvote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_upvote_proto_rawDescGZIP(), []int{1}
}

func (x *VoteResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_upvote_proto protoreflect.FileDescriptor

var file_upvote_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x22, 0xcb, 0x01, 0x0a, 0x0b, 0x56, 0x6f, 0x74, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x69, 0x72, 0x12, 0x44, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20,
	0x2e, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x24,
	0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x49, 0x52, 0x4d, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4e, 0x53, 0x57,
	0x45, 0x52, 0x10, 0x01, 0x22, 0x24, 0x0a, 0x0c, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x32, 0x44, 0x0a, 0x0d, 0x55, 0x70,
	0x76, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x56,
	0x6f, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x56, 0x6f, 0x74,
	0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x14, 0x2e, 0x75, 0x70, 0x76, 0x6f, 0x74,
	0x65, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x20, 0x5a, 0x1e, 0x2f, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x3b, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_upvote_proto_rawDescOnce sync.Once
	file_upvote_proto_rawDescData = file_upvote_proto_rawDesc
)

func file_upvote_proto_rawDescGZIP() []byte {
	file_upvote_proto_rawDescOnce.Do(func() {
		file_upvote_proto_rawDescData = protoimpl.X.CompressGZIP(file_upvote_proto_rawDescData)
	})
	return file_upvote_proto_rawDescData
}

var file_upvote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_upvote_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_upvote_proto_goTypes = []interface{}{
	(VotePayload_ResourceType)(0), // 0: upvote.VotePayload.ResourceType
	(*VotePayload)(nil),           // 1: upvote.VotePayload
	(*VoteResponse)(nil),          // 2: upvote.VoteResponse
}
var file_upvote_proto_depIdxs = []int32{
	0, // 0: upvote.VotePayload.resourceType:type_name -> upvote.VotePayload.ResourceType
	1, // 1: upvote.UpvoteService.Vote:input_type -> upvote.VotePayload
	2, // 2: upvote.UpvoteService.Vote:output_type -> upvote.VoteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_upvote_proto_init() }
func file_upvote_proto_init() {
	if File_upvote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_upvote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VotePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_upvote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_upvote_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upvote_proto_goTypes,
		DependencyIndexes: file_upvote_proto_depIdxs,
		EnumInfos:         file_upvote_proto_enumTypes,
		MessageInfos:      file_upvote_proto_msgTypes,
	}.Build()
	File_upvote_proto = out.File
	file_upvote_proto_rawDesc = nil
	file_upvote_proto_goTypes = nil
	file_upvote_proto_depIdxs = nil
}
